Repository AreaFiftyLAN/lancie-frontend, pull requests merged in 2022-03, with the labels that each got.

#707 Update terms and conditions in consultation with board
  src/lancie-ticket-page/lancie-terms-of-service-text.html
Labels: ready for review, priority:high

#708 Update sponsors
  data/database-tournaments.json
  data/official-tournaments.json
  images/logos/NintendoLogo.png
  src/lancie-home-page/lancie-home-page.html
Labels: enhancement

#709 Update all descriptions such that they are aligned with each other.
  data/official-tournaments.json
Labels: priority:high

#710 Update lancie-terms-of-service-text.html
  src/lancie-ticket-page/lancie-terms-of-service-text.html
Labels: priority:high
